image: kaiwinter/docker-java8-maven
stages:
  - Build
  - Tests
  - Deploy
cache:
  paths:
    - repo/
before_script:
  - export VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)


build:
  stage: Build
  script:
    - eval mvn clean compile package
    - mkdir output
    - cp LICENSE output/LICENSE
    - cp README.md output/README.md

    - cp target/ABOS-$VERSION-jar-with-dependencies.jar output/$VERSION.jar
  artifacts:
    paths:
      - output
  tags:
    - linux

Site:
  stage: Tests
  script:
    - eval mvn clean compile package
  artifacts:
    paths:
      - target/*-with-dependencies.jar
  tags:
    - linux
  only:
    - master
pages:
  stage: Tests
  script:
    - eval mvn site
    - cp -r target/site/* public
  artifacts:
    paths:
      - public
  tags:
    - linux
  only:
    - Develop
Deploy:
  stage: Deploy
  script:
    - eval mvn clean compile package
  artifacts:
    paths:
      - target/*-with-dependencies.jar
  tags:
    - linux
  only:
    - master
Deploy:
  stage: Deploy
  script:
    - eval mvn clean compile package
  artifacts:
    paths:
      - target/*-with-dependencies.jar
  tags:
    - linux
  only:
    - Develop


