image: kaiwinter/docker-java8-maven

java:
  script:
    - call mvn clean compile package
  artifacts:
    paths:
      - target/*-with-dependencies.jar
  tags:
    - windows
java:
  script:
    - eval mvn clean compile package
  artifacts:
    paths:
      - target/*-with-dependencies.jar
  tags:
    - linux